ApiBanco/BancoAppWeb/Models/Shared/DelTransaction.cs
namespace BancoAppWeb.Models.Shared
{
    public class DelTransaction
    {
    }
}

ApiBanco/BancoAppWeb/Models/Shared/ViewModelAddTransaction.cs
using User.Data.Models;

namespace BancoAppWeb.Models.Shared
{
    public class ViewModelAddTransaction
    {
        public string? userId { get; set; }
        public decimal Value { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public TransactionType? Type { get; set; }
        public string Attachment { get; set; }
    }



}

ApiBanco/BancoAppWeb/Models/Shared/ViewModelEditTransaction.cs
using User.Data.DTOs;

namespace BancoAppWeb.Models.Shared
{
    public class ViewModelEditTransaction
    {
            public int Id { get; set; }
            public string userId { get; set; }
            public decimal Value { get; set; }
            public string Title { get; set; }
            public string Description { get; set; }
            public string Attachment { get; set; }
        
    }
}

ApiBanco/BancoAppWeb/Controllers/Consumer/ApiController.cs
using Azure;
using BancoAppWeb.Models.Todolist;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web.WebPages;
using User.Data.DTOModel;

namespace BancoAppWeb.Controllers
{
    public class ApiController : Controller
    {
        private readonly HttpClient _httpClient;

        public ApiController(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        public IActionResult IndexTodoList()
        {
            var response = _httpClient.GetAsync("https://localhost:7072/api/todolist/getalllists").Result;

            var content = response.Content.ReadAsStringAsync().Result;
            var todolist = JsonSerializer.Deserialize<List<DTOTodoList>>(content);
            
            //var strJson = JsonSerializer.Serialize(todolist);


            var viewmodelhome = new ViewModelHomeTodo { dtoTodoList = todolist };

            return View("IndexTodoList", viewmodelhome);
        }

        public IActionResult ViewCard(int id)
        {
            var response = _httpClient.GetAsync($"https://localhost:7072/api/todolist/getbyid?listid={id}").Result;

            var content = response.Content.ReadAsStringAsync().Result;
            var todolist = JsonSerializer.Deserialize<ViewModelTask>(content);

            //var strJson = JsonSerializer.Serialize(todolist);
            //deveria receber um dto a partir da API, e aqui usar o mapper com o profile adequado e converter o DTO em uma view
            //como não recebemos um DTO vindo da API, convertemos diretamente o objeto recebido em JSON para uma view (o que é errado)


            return View("ViewCardTask", todolist);
        }

        public IActionResult Delettask(int id)
        {

           var a  = _httpClient.DeleteAsync($"https://localhost:7072/api/todolist/task/deletetask?taskid={id}").Result;

            var content = a.Content.ReadAsStringAsync().Result;
            int result = Int32.Parse(content);

            return ViewCard(result);
        }

        public IActionResult DeletList(int id)
        {

            var a = _httpClient.DeleteAsync($"https://localhost:7072/api/todolist/deletetodolist?todolistId={id}").Result;

            return IndexTodoList();
        }

        public IActionResult CreateTask(ViewModelAddTask viewmodeladd)
        {

            var response = _httpClient.PostAsJsonAsync<ViewModelAddTask>("https://localhost:7072/api/todolist/task/createtask", viewmodeladd).Result;
            if (response.IsSuccessStatusCode)
            {
                return ViewCard(viewmodeladd.Id);
            }
            else
            {
                return ViewCard(viewmodeladd.Id);
            }

        }


        public IActionResult CompleteTask(int Id, int listId)
        {
            var content = new StringContent(string.Empty);
            _ =  _httpClient.PostAsync($"https://localhost:7072/api/todolist/task/complete?taskid={Id}",content).Result;


            return ViewCard(listId);
        }


        public IActionResult GoToViewAddList( )
        {
            return View("ViewAddList");
        }

        public IActionResult CreateList(ViewModelAddList viewmodeladd)
        {
          viewmodeladd.color = 10;
          viewmodeladd.tasks = new List<DTOTodoListTask>();
          var response = _httpClient.PostAsJsonAsync<ViewModelAddList>("https://localhost:7072/api/todolist/createlist", viewmodeladd).Result;

           return IndexTodoList();
        }

    }
}

ApiBanco/BancoAppWeb/Controllers/DashboardController.cs
using ApiBanco.Bussines.Services;
using BancoAppWeb.Factory;
using BancoAppWeb.Models;
using BancoAppWeb.Models.Shared;
using BancoAppWeb.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel;
using System.Diagnostics;
using User.Data.DTOModel;
using User.Data.DTOs;
using User.Data.Entityes;
using User.Data.Models;

namespace BancoAppWeb.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;
        private readonly IDashboardService _dashboardService;
        private readonly ITransactionService _transactionService;
        private readonly IViewFactory _viewFactory;
        public DashboardController(ILogger<DashboardController> logger, IDashboardService dashboardService, IViewFactory viewFactory, ITransactionService transactionService)
        {
            _logger = logger;
            _dashboardService = dashboardService;
            _viewFactory = viewFactory;
            _transactionService = transactionService;
        }



        public IActionResult Login()
        {

            return View("Login");
        }

        public IActionResult Loginfinal(ViewModelLogin login)
        {

            var user = _dashboardService.GetDashboardByUserId(login.idUser, TimeFrame.Weekly);

            if (user.idUser == "empty")
            {
                _dashboardService.AddUser(new DTOAccount
                {
                    userId = login.idUser,
                    Fname  = login.fName,
                    Lname = login.lName,
                });

                user = _dashboardService.GetDashboardByUserId(login.idUser, TimeFrame.Weekly);
            }

            return RedirectToAction("Index", new { UID = user.idUser, timeFrame = TimeFrame.Weekly });
        }


        public IActionResult Index(string UID, TimeFrame timeFrame)
        {

           var user = _dashboardService.GetDashboardByUserId(UID, timeFrame);

            var viewuser = _viewFactory.ViewModelDashboard(user);

            return View(viewuser);

        }
        public IActionResult AddTransaction(ViewModelAddTransaction viewModelAdd)
        {
            var viewTranDTO = _viewFactory.ViewTransToDTOTransact(viewModelAdd);
            _transactionService.AddTransaction(viewTranDTO);
            return RedirectToAction("Index", new { uid = viewModelAdd.userId, timeFrame = TimeFrame.Weekly });
        }

        public IActionResult RemoveTransaction(int Id)
        {
            var trasactiondto = _transactionService.GetTransactionByID(Id);
            var uid = trasactiondto.userId;
            _transactionService.DeleteTransactionbyId(Id);

            return RedirectToAction("Index", new { uid = uid, timeFrame = TimeFrame.Weekly });
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApiBanco/BancoAppWeb/Views/Shared/AddExpense.cshtml
@using User.Data.Entityes;
@using User.Data.Models;
@model string
@{
    ViewData["Title"] = "AddExpense";

}


<!DOCTYPE htmlA>
<html>

<body>
    <div class="sidebar">
        <a href="@Url.Action("Index", "Dashboard", new { UID = Model, timeFrame = TimeFrame.Weekly }))">Dashboard</a>
        <a href="@Url.Action("Index", "Transaction", new { UID = Model, transactionType = TransactionType.all })">Transactions</a>

    </div>
    <div class="content">

        <form class="add-expense-form" method="POST" action="@Url.Action("AddExpenseTransaction", "Transaction",new {uid = Model})">
            <div class="add-expense-container">
                <h1 class="add-expense-title">expense</h1>
                <div class="add-expense-form">
                    <div class="add-expense-form-item">
                        <label for="value" class="add-expense-form-label">Value</label>
                        <input type="text" id="value" name="value" class="add-expense-form-input" placeholder="€ xx">
                    </div>
                    <div class="add-expense-form-item">
                        <label for="date" class="add-expense-form-label">Date</label>
                        <input type="text" id="date" name="date" class="add-expense-form-input" placeholder="31/12/2023">
                    </div>
                    <div class="add-expense-form-item">
                        <label for="title" class="add-expense-form-label">Title</label>
                        <input type="text" id="title" name="title" class="add-inexpensecome-form-input" placeholder="Market">
                    </div>
                    <div class="add-expense-form-item">
                        <label for="description" class="add-expense-form-label">Description</label>
                        <textarea id="description" name="description" class="add-expense-form-textarea" placeholder="Lorem ipsum dolor sit amet"></textarea>
                    </div>
                </div>

                <div class="add-expense-attachment">
                    <h2 class="add-expense-attachment-title">Attachment</h2>
                    <div class="add-expense-attachment-input-container">
                        <input type="file" id="attachment-input" class="add-expense-attachment-input">
                        <label for="attachment-input" class="add-expense-attachment-label">Select file</label>

                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Add Expense</button>
        </form>
    </div>
</body>
</html> 

ApiBanco/BancoAppWeb/Views/Shared/AddIncome.cshtml
@using User.Data.Entityes;
@using User.Data.Models;
@model string
@{
    ViewData["Title"] = "AddIncome";
}


<!DOCTYPE htmlA>
<html>

<body>
    <div class="sidebar">
        <a href="@Url.Action("Index", "Dashboard", new { UID = Model, timeFrame = TimeFrame.Weekly }))">Dashboard</a>
        <a href="@Url.Action("Index", "Transaction", new { UID = Model, transactionType = TransactionType.all })">Transactions</a>

    </div>
    <div class="content">

        <form class="add-income-form" method="POST" action="@Url.Action("AddIncomeTransaction", "Transaction", new {uid = Model})">
            <div class="add-income-container">
                <h1 class="add-income-title">Income</h1>
                <div class="add-income-form">
                    <div class="add-income-form-item">
                        <label for="value" class="add-income-form-label">Value</label>
                        <input type="text" id="value" name="value" class="add-income-form-input" placeholder="€ xx">
                    </div>
                    <div class="add-income-form-item">
                        <label for="date" class="add-income-form-label">Date</label>
                        <input type="text" id="date" name="date" class="add-income-form-input" placeholder="31/12/2023">
                    </div>
                    <div class="add-income-form-item">
                        <label for="title" class="add-income-form-label">Title</label>
                        <input type="text" id="title" name="title" class="add-income-form-input" placeholder="Market">
                    </div>
                    <div class="add-income-form-item">
                        <label for="description" class="add-income-form-label">Description</label>
                        <textarea id="description" name="description" class="add-income-form-textarea" placeholder="Lorem ipsum dolor sit amet"></textarea>
                    </div>
                </div>

                <div class="add-income-attachment">
                    <h2 class="add-income-attachment-title">Attachment</h2>
                    <div class="add-income-attachment-input-container">
                        <input type="file" id="attachment-input" class="add-income-attachment-input">
                        <label for="attachment-input" class="add-income-attachment-label">Select file</label>

                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Add Income</button>
        </form>
    </div>
</body>
</html> 

ApiBanco/BancoAppWeb/Views/Shared/EditTransaction.cshtml
@using BancoAppWeb.Models.Shared;

@{
    @model ViewModelEditTransaction;
    ViewData["Title"] = "EditTransaction";

}


<!DOCTYPE htmlA>
<html>

<body>
    <div class="sidebar">
        <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
        <a href="@Url.Action("Index", "Transaction")">Transactions</a>
        <a href="@Url.Action("AddIncome", "Transaction")">Add Income</a>
        <a href="@Url.Action("AddExpense", "Transaction")">Add Expense</a>

    </div>
    <div class="content">

        <form class="edit-transaction-form" method="POST" action="@Url.Action("EditTransactionFinal", "Transaction", new {id = @Model.Id})">
            <div class="edit-transaction-container">
                <h1 class="edit-transaction-title">editTransaction</h1>
                <div class="edit-transaction-form">
                    <div class="edit-transaction-form-item">
                        <label for="value" class="edit-transaction-form-label">Value</label>
                        <input type="text" id="value" name="value" class="edit-transactione-form-input" placeholder="€@Model.Value">
                    </div>
                    <div class="edit-transaction-form-item">
                        <label for="title" class="edit-transaction-form-label">Title</label>
                        <input type="text" id="title" name="title" class="edit-transaction-form-input" placeholder="@Model.Title">
                    </div>
                    <div class="edit-transaction-form-item">
                        <label for="description" class="edit-transaction-form-label">Description</label>
                        <textarea id="description" name="description" class="edit-transaction-form-textarea" placeholder="@Model.Description"></textarea>
                    </div>
                </div>

                <div class="edit-transaction-attachment">
                    <h2 class="edit-transaction-attachment-title">Attachment</h2>
                    <div class="edit-transaction-attachment-input-container">
                        <input type="file" id="attachment-input" class="edit-transaction-attachment-input">
                        <label for="attachment-input" class="edit-transaction-attachment-label">Select file</label>

                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Edit Transaction</button>
        </form>
    </div>
</body>
</html> 

ApiBanco/BancoAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BancoAppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/add-income.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BancoAppWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/add-income.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BancoAppWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" href="@Url.Action("IndexTodoList", "Api")">TodoList</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>